/**
 * Populates missing token values on all country documents in Firestore.
 *
 * Adds the 39 tokens that are absent from all 50 countries. Never overwrites
 * existing non-null token values. Runs as a dry-run by default; pass --write
 * to commit to Firestore.
 *
 * Token categories covered:
 *   - legislative: legislature_speaker, upper_house_leader, governing_party_ideology
 *   - executive:   head_of_state_title
 *   - military:    ground_forces_branch, maritime_branch, air_branch, marine_branch,
 *                  space_branch, paramilitary_branch, coast_guard_branch, cyber_branch,
 *                  intel_branch, strategic_nuclear_branch, coalition_name,
 *                  armed_forces_name, military_chief_title
 *   - economic:    main_export, main_import, major_industry
 *   - geography:   city_name, state_name, locale_type, locale_name, region_type,
 *                  terrain, short_distance, medium_distance, long_distance
 *   - context:     scenario_theme, crisis_type
 *   - relationships: regional_bloc
 */

import { initializeApp } from 'firebase-admin/app';
import { getFirestore, FieldValue } from 'firebase-admin/firestore';

const WRITE = process.argv.includes('--write');

// null = branch doesn't exist for this country (token marked as optional/null)
type CountryTokens = Record<string, string | null>;

// ── Per-country token data ─────────────────────────────────────────────────
// Keys match Firestore document IDs (2-letter ISO codes, lowercase)
// Each object ONLY contains the 39 new tokens; existing tokens are untouched.

export const COUNTRY_DATA: Record<string, CountryTokens> = {
  au: {
    head_of_state_title: 'Governor-General of Australia',
    legislature_speaker: 'Speaker of the House of Representatives',
    upper_house_leader: 'President of the Senate',
    governing_party_ideology: 'centre-left social democracy',
    ground_forces_branch: 'Australian Army',
    maritime_branch: 'Royal Australian Navy',
    air_branch: 'Royal Australian Air Force',
    marine_branch: null,
    space_branch: 'Australian Space Agency',
    paramilitary_branch: null,
    coast_guard_branch: 'Australian Border Force',
    cyber_branch: 'Australian Cyber Security Centre',
    intel_branch: 'Australian Signals Directorate',
    strategic_nuclear_branch: null,
    armed_forces_name: 'Australian Defence Force',
    military_chief_title: 'Chief of the Defence Force',
    coalition_name: 'AUKUS partnership',
    main_export: 'iron ore and coal',
    main_import: 'refined petroleum and vehicles',
    major_industry: 'mining and resources sector',
    city_name: 'Melbourne',
    state_name: 'New South Wales',
    locale_type: 'state capital',
    locale_name: 'Sydney',
    region_type: 'Indo-Pacific region',
    terrain: 'coastal and outback',
    short_distance: '300 kilometres',
    medium_distance: '900 kilometres',
    long_distance: '3,500 kilometres',
    scenario_theme: 'regional security',
    crisis_type: 'natural disaster',
    regional_bloc: 'ASEAN dialogue partner',
  },
  br: {
    head_of_state_title: 'President of the Federative Republic of Brazil',
    legislature_speaker: 'President of the Chamber of Deputies',
    upper_house_leader: 'President of the Federal Senate',
    governing_party_ideology: 'left-wing social democracy',
    ground_forces_branch: 'Brazilian Army',
    maritime_branch: 'Brazilian Navy',
    air_branch: 'Brazilian Air Force',
    marine_branch: 'Brazilian Marine Corps',
    space_branch: 'Brazilian Space Agency',
    paramilitary_branch: null,
    coast_guard_branch: null,
    cyber_branch: 'Brazilian Cyber Defense Command',
    intel_branch: null,
    strategic_nuclear_branch: null,
    armed_forces_name: 'Brazilian Armed Forces',
    military_chief_title: 'Chief of the Joint Chiefs of Staff',
    coalition_name: null,
    main_export: 'soybeans and iron ore',
    main_import: 'fuels and machinery',
    major_industry: 'agricultural and energy sector',
    city_name: 'São Paulo',
    state_name: 'São Paulo State',
    locale_type: 'industrial metropolis',
    locale_name: 'São Paulo',
    region_type: 'Amazon basin',
    terrain: 'tropical rainforest and savanna',
    short_distance: '400 kilometres',
    medium_distance: '1,200 kilometres',
    long_distance: '3,000 kilometres',
    scenario_theme: 'environmental governance',
    crisis_type: 'deforestation crisis',
    regional_bloc: 'MERCOSUR',
  },
  ca: {
    head_of_state_title: 'Governor General of Canada',
    legislature_speaker: 'Speaker of the House of Commons',
    upper_house_leader: 'Speaker of the Senate',
    governing_party_ideology: 'centre-left liberalism',
    ground_forces_branch: 'Canadian Army',
    maritime_branch: 'Royal Canadian Navy',
    air_branch: 'Royal Canadian Air Force',
    marine_branch: null,
    space_branch: 'Canadian Space Agency',
    paramilitary_branch: null,
    coast_guard_branch: 'Canadian Coast Guard',
    cyber_branch: 'Canadian Centre for Cyber Security',
    intel_branch: 'Communications Security Establishment',
    strategic_nuclear_branch: null,
    armed_forces_name: 'Canadian Armed Forces',
    military_chief_title: 'Chief of the Defence Staff',
    coalition_name: 'NATO northern flank',
    main_export: 'oil sands crude and natural gas',
    main_import: 'motor vehicles and consumer goods',
    major_industry: 'energy and natural resources sector',
    city_name: 'Toronto',
    state_name: 'Ontario',
    locale_type: 'provincial capital',
    locale_name: 'Toronto',
    region_type: 'Great Lakes region',
    terrain: 'boreal forest and prairie',
    short_distance: '400 kilometres',
    medium_distance: '1,500 kilometres',
    long_distance: '4,500 kilometres',
    scenario_theme: 'Arctic sovereignty',
    crisis_type: 'energy security crisis',
    regional_bloc: 'G7',
  },
  cn: {
    head_of_state_title: 'President of the People\'s Republic of China',
    legislature_speaker: 'Chairman of the Standing Committee of the NPC',
    upper_house_leader: null,
    governing_party_ideology: 'Marxist-Leninist with Chinese characteristics',
    ground_forces_branch: 'People\'s Liberation Army Ground Force',
    maritime_branch: 'People\'s Liberation Army Navy',
    air_branch: 'People\'s Liberation Army Air Force',
    marine_branch: 'PLA Marine Corps',
    space_branch: 'PLA Strategic Support Force',
    paramilitary_branch: 'People\'s Armed Police',
    coast_guard_branch: 'China Coast Guard',
    cyber_branch: 'PLA Network Systems Department',
    intel_branch: 'Ministry of State Security',
    strategic_nuclear_branch: 'PLA Rocket Force',
    armed_forces_name: 'People\'s Liberation Army',
    military_chief_title: 'Chairman of the Central Military Commission',
    coalition_name: 'Shanghai Cooperation Organisation',
    main_export: 'electronics and manufactured goods',
    main_import: 'semiconductors and energy resources',
    major_industry: 'manufacturing and technology sector',
    city_name: 'Shanghai',
    state_name: 'Guangdong Province',
    locale_type: 'major port city',
    locale_name: 'Shanghai',
    region_type: 'coastal economic zone',
    terrain: 'coastal plains and river delta',
    short_distance: '500 kilometres',
    medium_distance: '2,000 kilometres',
    long_distance: '5,000 kilometres',
    scenario_theme: 'regional hegemony',
    crisis_type: 'territorial dispute',
    regional_bloc: 'Shanghai Cooperation Organisation',
  },
  de: {
    head_of_state_title: 'Federal President of Germany',
    legislature_speaker: 'President of the Bundestag',
    upper_house_leader: 'President of the Bundesrat',
    governing_party_ideology: 'Christian democratic conservatism',
    ground_forces_branch: 'German Army',
    maritime_branch: 'German Navy',
    air_branch: 'German Air Force',
    marine_branch: null,
    space_branch: null,
    paramilitary_branch: null,
    coast_guard_branch: 'Federal Police Maritime',
    cyber_branch: 'Cyber and Information Domain Service',
    intel_branch: 'Federal Intelligence Service',
    strategic_nuclear_branch: null,
    armed_forces_name: 'Bundeswehr',
    military_chief_title: 'Inspector General of the Bundeswehr',
    coalition_name: 'NATO central pillar',
    main_export: 'motor vehicles and machinery',
    main_import: 'energy and electronics',
    major_industry: 'automotive and engineering sector',
    city_name: 'Munich',
    state_name: 'Bavaria',
    locale_type: 'industrial state capital',
    locale_name: 'Munich',
    region_type: 'Central European heartland',
    terrain: 'northern plains and Alpine foothills',
    short_distance: '200 kilometres',
    medium_distance: '600 kilometres',
    long_distance: '1,500 kilometres',
    scenario_theme: 'European integration',
    crisis_type: 'energy dependency crisis',
    regional_bloc: 'European Union',
  },
  fr: {
    head_of_state_title: 'President of the French Republic',
    legislature_speaker: 'President of the National Assembly',
    upper_house_leader: 'President of the Senate',
    governing_party_ideology: 'centrist liberal',
    ground_forces_branch: 'French Army',
    maritime_branch: 'French Navy',
    air_branch: 'French Air and Space Force',
    marine_branch: 'French Marine Corps',
    space_branch: 'National Centre for Space Studies',
    paramilitary_branch: 'National Gendarmerie',
    coast_guard_branch: 'Maritime Gendarmerie',
    cyber_branch: 'National Cybersecurity Agency',
    intel_branch: 'General Directorate for External Security',
    strategic_nuclear_branch: 'Strategic Nuclear Forces',
    armed_forces_name: 'French Armed Forces',
    military_chief_title: 'Chief of the Defence Staff',
    coalition_name: 'EU rapid reaction force',
    main_export: 'aerospace equipment and luxury goods',
    main_import: 'energy and electronics',
    major_industry: 'aerospace and luxury goods sector',
    city_name: 'Lyon',
    state_name: 'Île-de-France',
    locale_type: 'industrial city',
    locale_name: 'Lyon',
    region_type: 'Western European heartland',
    terrain: 'northern plains and Alpine south',
    short_distance: '200 kilometres',
    medium_distance: '600 kilometres',
    long_distance: '1,500 kilometres',
    scenario_theme: 'European leadership',
    crisis_type: 'social unrest',
    regional_bloc: 'European Union',
  },
  gb: {
    head_of_state_title: 'His Majesty the King',
    legislature_speaker: 'Speaker of the House of Commons',
    upper_house_leader: 'Lord Speaker',
    governing_party_ideology: 'centre-left social democracy',
    ground_forces_branch: 'British Army',
    maritime_branch: 'Royal Navy',
    air_branch: 'Royal Air Force',
    marine_branch: 'Royal Marines',
    space_branch: 'UK Space Agency',
    paramilitary_branch: null,
    coast_guard_branch: 'His Majesty\'s Coastguard',
    cyber_branch: 'National Cyber Force',
    intel_branch: 'Government Communications Headquarters',
    strategic_nuclear_branch: 'Royal Navy Continuous At-Sea Deterrent',
    armed_forces_name: 'His Majesty\'s Armed Forces',
    military_chief_title: 'Chief of the Defence Staff',
    coalition_name: 'Five Eyes intelligence alliance',
    main_export: 'financial services and aerospace',
    main_import: 'consumer goods and vehicles',
    major_industry: 'financial and professional services',
    city_name: 'Manchester',
    state_name: 'England',
    locale_type: 'northern industrial city',
    locale_name: 'Manchester',
    region_type: 'North Atlantic archipelago',
    terrain: 'rolling hills and coastal lowlands',
    short_distance: '200 kilometres',
    medium_distance: '600 kilometres',
    long_distance: '1,500 kilometres',
    scenario_theme: 'post-Brexit realignment',
    crisis_type: 'constitutional crisis',
    regional_bloc: 'Five Eyes',
  },
  gh: {
    head_of_state_title: 'President of the Republic of Ghana',
    legislature_speaker: 'Speaker of Parliament',
    upper_house_leader: null,
    governing_party_ideology: 'social democratic',
    ground_forces_branch: 'Ghana Army',
    maritime_branch: 'Ghana Navy',
    air_branch: 'Ghana Air Force',
    marine_branch: null,
    space_branch: null,
    paramilitary_branch: null,
    coast_guard_branch: null,
    cyber_branch: null,
    intel_branch: 'Bureau of National Investigations',
    strategic_nuclear_branch: null,
    armed_forces_name: 'Ghana Armed Forces',
    military_chief_title: 'Chief of Defence Staff',
    coalition_name: 'ECOWAS security framework',
    main_export: 'gold and cocoa',
    main_import: 'machinery and oil',
    major_industry: 'mining and agricultural exports',
    city_name: 'Kumasi',
    state_name: 'Greater Accra Region',
    locale_type: 'commercial hub',
    locale_name: 'Kumasi',
    region_type: 'West African coast',
    terrain: 'tropical forest and savanna',
    short_distance: '150 kilometres',
    medium_distance: '400 kilometres',
    long_distance: '1,000 kilometres',
    scenario_theme: 'democratic governance',
    crisis_type: 'debt crisis',
    regional_bloc: 'ECOWAS',
  },
  il: {
    head_of_state_title: 'President of the State of Israel',
    legislature_speaker: 'Speaker of the Knesset',
    upper_house_leader: null,
    governing_party_ideology: 'right-wing nationalism',
    ground_forces_branch: 'Israel Defense Forces Ground Command',
    maritime_branch: 'Israeli Navy',
    air_branch: 'Israeli Air Force',
    marine_branch: 'Shayetet 13',
    space_branch: 'Israel Space Agency',
    paramilitary_branch: 'Border Police',
    coast_guard_branch: null,
    cyber_branch: 'National Cyber Directorate',
    intel_branch: 'Mossad',
    strategic_nuclear_branch: null,
    armed_forces_name: 'Israel Defense Forces',
    military_chief_title: 'Chief of the General Staff',
    coalition_name: 'Abraham Accords security framework',
    main_export: 'diamonds and technology',
    main_import: 'fuels and machinery',
    major_industry: 'technology and defense industries',
    city_name: 'Tel Aviv',
    state_name: 'Tel Aviv District',
    locale_type: 'technology hub',
    locale_name: 'Tel Aviv',
    region_type: 'Eastern Mediterranean',
    terrain: 'coastal plains and Negev desert',
    short_distance: '100 kilometres',
    medium_distance: '300 kilometres',
    long_distance: '700 kilometres',
    scenario_theme: 'regional security',
    crisis_type: 'military escalation',
    regional_bloc: 'Abraham Accords',
  },
  in: {
    leader_title: 'Prime Minister',
    head_of_state_title: 'President',
    country_adjective: 'Indian',
    country_full_name: 'Republic of India',
    legislature: 'Parliament',
    upper_house: 'Rajya Sabha',
    lower_house: 'Lok Sabha',
    governing_party: 'Bharatiya Janata Party',
    governing_party_short: 'BJP',
    opposition_party: 'Indian National Congress',
    central_bank: 'Reserve Bank of India',
    currency: 'Indian Rupee',
    currency_code: 'INR',
    armed_forces_name: 'Indian Armed Forces',
    ground_forces_branch: 'Indian Army',
    maritime_branch: 'Indian Navy',
    air_branch: 'Indian Air Force',
    strategic_nuclear_branch: 'Strategic Forces Command',
    intelligence_agency: 'Research and Analysis Wing',
    domestic_intelligence: 'Intelligence Bureau',
    security_council: 'Cabinet Committee on Security',
    police_force: 'Central Reserve Police Force',
    military_chief_title: 'Chief of Defence Staff',
    press_role: 'Principal Spokesperson',
    supreme_court: 'Supreme Court of India',
    attorney_general: 'Attorney General of India',
    audit_body: 'Comptroller and Auditor General',
    major_industry: 'information technology and services',
    economic_bloc: 'G20',
    primary_ally: 'United States',
    primary_adversary: 'Pakistan',
    border_rival_country: 'China',
    key_alliance: 'Quad',
  },
  ir: {
    head_of_state_title: 'Supreme Leader of Iran',
    legislature_speaker: 'Speaker of the Islamic Consultative Assembly',
    upper_house_leader: null,
    governing_party_ideology: 'Islamist theocracy',
    ground_forces_branch: 'Islamic Republic of Iran Army Ground Forces',
    maritime_branch: 'Islamic Republic of Iran Navy',
    air_branch: 'Islamic Republic of Iran Air Force',
    marine_branch: null,
    space_branch: 'Iranian Space Agency',
    paramilitary_branch: 'Islamic Revolutionary Guard Corps',
    coast_guard_branch: 'IRGC Navy',
    cyber_branch: 'Passive Defense Organization',
    intel_branch: 'Ministry of Intelligence',
    strategic_nuclear_branch: null,
    armed_forces_name: 'Islamic Republic of Iran Armed Forces',
    military_chief_title: 'Chief of Staff of the Iranian Armed Forces',
    coalition_name: 'Axis of Resistance',
    main_export: 'petroleum and petrochemicals',
    main_import: 'machinery and consumer goods',
    major_industry: 'oil and gas sector',
    city_name: 'Isfahan',
    state_name: 'Tehran Province',
    locale_type: 'historic city',
    locale_name: 'Isfahan',
    region_type: 'Persian Gulf region',
    terrain: 'arid plateau and Zagros mountains',
    short_distance: '200 kilometres',
    medium_distance: '700 kilometres',
    long_distance: '1,800 kilometres',
    scenario_theme: 'nuclear diplomacy',
    crisis_type: 'sanctions pressure',
    regional_bloc: 'Shanghai Cooperation Organisation',
  },
  jm: {
    head_of_state_title: 'Governor-General of Jamaica',
    legislature_speaker: 'Speaker of the House of Representatives',
    upper_house_leader: 'President of the Senate',
    governing_party_ideology: 'centre-right social conservatism',
    ground_forces_branch: 'Jamaica Regiment',
    maritime_branch: 'Jamaica Coast Guard',
    air_branch: 'Jamaica Air Wing',
    marine_branch: null,
    space_branch: null,
    paramilitary_branch: null,
    coast_guard_branch: 'Jamaica Coast Guard',
    cyber_branch: null,
    intel_branch: null,
    strategic_nuclear_branch: null,
    armed_forces_name: 'Jamaica Defence Force',
    military_chief_title: 'Chief of Defence Staff',
    coalition_name: 'CARICOM security framework',
    main_export: 'alumina and bauxite',
    main_import: 'fuel and machinery',
    major_industry: 'tourism and bauxite mining',
    city_name: 'Montego Bay',
    state_name: 'Saint Andrew Parish',
    locale_type: 'tourist city',
    locale_name: 'Montego Bay',
    region_type: 'Caribbean island',
    terrain: 'tropical mountains and coastal plains',
    short_distance: '80 kilometres',
    medium_distance: '250 kilometres',
    long_distance: '700 kilometres',
    scenario_theme: 'gang violence and security',
    crisis_type: 'organized crime crisis',
    regional_bloc: 'CARICOM',
  },
  jp: {
    head_of_state_title: 'Emperor of Japan',
    legislature_speaker: 'Speaker of the House of Representatives',
    upper_house_leader: 'President of the House of Councillors',
    governing_party_ideology: 'conservative liberal democracy',
    ground_forces_branch: 'Japan Ground Self-Defense Force',
    maritime_branch: 'Japan Maritime Self-Defense Force',
    air_branch: 'Japan Air Self-Defense Force',
    marine_branch: 'Amphibious Rapid Deployment Brigade',
    space_branch: 'Japan Aerospace Exploration Agency',
    paramilitary_branch: null,
    coast_guard_branch: 'Japan Coast Guard',
    cyber_branch: 'Self-Defense Forces Cyber Defense Command',
    intel_branch: 'Cabinet Intelligence and Research Office',
    strategic_nuclear_branch: null,
    armed_forces_name: 'Japan Self-Defense Forces',
    military_chief_title: 'Chairman of the Joint Chiefs of Staff',
    coalition_name: 'US-Japan security alliance',
    main_export: 'motor vehicles and electronics',
    main_import: 'energy and raw materials',
    major_industry: 'automotive and electronics sector',
    city_name: 'Osaka',
    state_name: 'Osaka Prefecture',
    locale_type: 'commercial city',
    locale_name: 'Osaka',
    region_type: 'East Asian archipelago',
    terrain: 'mountainous volcanic islands',
    short_distance: '200 kilometres',
    medium_distance: '600 kilometres',
    long_distance: '1,500 kilometres',
    scenario_theme: 'rearmament and defense',
    crisis_type: 'North Korea missile crisis',
    regional_bloc: 'Quad',
  },
  kr: {
    head_of_state_title: 'President of the Republic of Korea',
    legislature_speaker: 'Speaker of the National Assembly',
    upper_house_leader: null,
    governing_party_ideology: 'progressive centre-left',
    ground_forces_branch: 'Republic of Korea Army',
    maritime_branch: 'Republic of Korea Navy',
    air_branch: 'Republic of Korea Air Force',
    marine_branch: 'Republic of Korea Marine Corps',
    space_branch: 'Korea Aerospace Research Institute',
    paramilitary_branch: null,
    coast_guard_branch: 'Korea Coast Guard',
    cyber_branch: 'Defense Security Support Command',
    intel_branch: 'National Intelligence Service',
    strategic_nuclear_branch: null,
    armed_forces_name: 'Republic of Korea Armed Forces',
    military_chief_title: 'Chairman of the Joint Chiefs of Staff',
    coalition_name: 'US-ROK Combined Forces Command',
    main_export: 'semiconductors and motor vehicles',
    main_import: 'crude oil and semiconductors',
    major_industry: 'semiconductor and shipbuilding sector',
    city_name: 'Busan',
    state_name: 'Gyeonggi Province',
    locale_type: 'port city',
    locale_name: 'Busan',
    region_type: 'Korean peninsula',
    terrain: 'mountainous with coastal plains',
    short_distance: '200 kilometres',
    medium_distance: '500 kilometres',
    long_distance: '1,200 kilometres',
    scenario_theme: 'inter-Korean relations',
    crisis_type: 'North Korea provocation',
    regional_bloc: 'Quad',
  },
  mx: {
    head_of_state_title: 'President of the United Mexican States',
    legislature_speaker: 'President of the Chamber of Deputies',
    upper_house_leader: 'President of the Senate',
    governing_party_ideology: 'left-wing social democracy',
    ground_forces_branch: 'Mexican Army',
    maritime_branch: 'Mexican Navy',
    air_branch: 'Mexican Air Force',
    marine_branch: 'Mexican Marine Corps',
    space_branch: 'Mexican Space Agency',
    paramilitary_branch: 'National Guard',
    coast_guard_branch: 'Mexican Coast Guard',
    cyber_branch: null,
    intel_branch: 'National Intelligence Centre',
    strategic_nuclear_branch: null,
    armed_forces_name: 'Mexican Armed Forces',
    military_chief_title: 'Secretary of National Defense',
    coalition_name: null,
    main_export: 'motor vehicles and petroleum',
    main_import: 'machinery and electronics',
    major_industry: 'automotive and energy sector',
    city_name: 'Guadalajara',
    state_name: 'Jalisco State',
    locale_type: 'industrial city',
    locale_name: 'Guadalajara',
    region_type: 'Central American border',
    terrain: 'high plateau and tropical coasts',
    short_distance: '300 kilometres',
    medium_distance: '900 kilometres',
    long_distance: '2,500 kilometres',
    scenario_theme: 'security and cartels',
    crisis_type: 'cartel violence',
    regional_bloc: 'USMCA',
  },
  ng: {
    head_of_state_title: 'President of the Federal Republic of Nigeria',
    legislature_speaker: 'Speaker of the House of Representatives',
    upper_house_leader: 'President of the Senate',
    governing_party_ideology: 'centre-right progressive conservatism',
    ground_forces_branch: 'Nigerian Army',
    maritime_branch: 'Nigerian Navy',
    air_branch: 'Nigerian Air Force',
    marine_branch: null,
    space_branch: 'National Space Research and Development Agency',
    paramilitary_branch: null,
    coast_guard_branch: null,
    cyber_branch: null,
    intel_branch: 'Department of State Services',
    strategic_nuclear_branch: null,
    armed_forces_name: 'Nigerian Armed Forces',
    military_chief_title: 'Chief of Defence Staff',
    coalition_name: 'ECOWAS security framework',
    main_export: 'crude oil and petroleum products',
    main_import: 'machinery and transport equipment',
    major_industry: 'oil and gas sector',
    city_name: 'Lagos',
    state_name: 'Lagos State',
    locale_type: 'commercial megacity',
    locale_name: 'Lagos',
    region_type: 'West African coast',
    terrain: 'Niger Delta and savanna',
    short_distance: '200 kilometres',
    medium_distance: '700 kilometres',
    long_distance: '2,000 kilometres',
    scenario_theme: 'energy and governance',
    crisis_type: 'insurgency in the north',
    regional_bloc: 'ECOWAS',
  },
  ru: {
    head_of_state_title: 'President of the Russian Federation',
    legislature_speaker: 'Chairman of the State Duma',
    upper_house_leader: 'Chairman of the Federation Council',
    governing_party_ideology: 'statist authoritarian nationalism',
    ground_forces_branch: 'Russian Ground Forces',
    maritime_branch: 'Russian Navy',
    air_branch: 'Russian Aerospace Forces',
    marine_branch: 'Russian Naval Infantry',
    space_branch: 'Roscosmos',
    paramilitary_branch: 'Russian National Guard',
    coast_guard_branch: 'Federal Security Service Coast Guard',
    cyber_branch: 'Federal Security Service Cyber Unit',
    intel_branch: 'Foreign Intelligence Service',
    strategic_nuclear_branch: 'Russian Strategic Missile Forces',
    armed_forces_name: 'Russian Armed Forces',
    military_chief_title: 'Chief of the General Staff',
    coalition_name: 'Collective Security Treaty Organisation',
    main_export: 'petroleum and natural gas',
    main_import: 'machinery and electronics',
    major_industry: 'energy and defense industry',
    city_name: 'Saint Petersburg',
    state_name: 'Moscow Oblast',
    locale_type: 'historic imperial city',
    locale_name: 'Saint Petersburg',
    region_type: 'Eurasian heartland',
    terrain: 'vast steppe and taiga',
    short_distance: '500 kilometres',
    medium_distance: '2,000 kilometres',
    long_distance: '6,000 kilometres',
    scenario_theme: 'great power competition',
    crisis_type: 'military escalation',
    regional_bloc: 'Collective Security Treaty Organisation',
  },
  sa: {
    head_of_state_title: 'King and Prime Minister of Saudi Arabia',
    legislature_speaker: 'Speaker of the Consultative Assembly',
    upper_house_leader: null,
    governing_party_ideology: 'Islamic absolute monarchy',
    ground_forces_branch: 'Royal Saudi Land Forces',
    maritime_branch: 'Royal Saudi Naval Forces',
    air_branch: 'Royal Saudi Air Force',
    marine_branch: 'Royal Saudi Marine Forces',
    space_branch: 'Saudi Space Agency',
    paramilitary_branch: 'Saudi Arabian National Guard',
    coast_guard_branch: 'Saudi Coast Guard',
    cyber_branch: 'National Cybersecurity Authority',
    intel_branch: 'General Directorate of Investigation',
    strategic_nuclear_branch: null,
    armed_forces_name: 'Royal Saudi Armed Forces',
    military_chief_title: 'Chief of the General Staff',
    coalition_name: 'Gulf Cooperation Council',
    main_export: 'crude oil and petroleum products',
    main_import: 'machinery and vehicles',
    major_industry: 'oil and petrochemical sector',
    city_name: 'Jeddah',
    state_name: 'Riyadh Province',
    locale_type: 'commercial port city',
    locale_name: 'Jeddah',
    region_type: 'Arabian Peninsula',
    terrain: 'arid desert and Red Sea coast',
    short_distance: '200 kilometres',
    medium_distance: '700 kilometres',
    long_distance: '2,000 kilometres',
    scenario_theme: 'Vision 2030 diversification',
    crisis_type: 'oil price shock',
    regional_bloc: 'Gulf Cooperation Council',
  },
  tr: {
    head_of_state_title: 'President of the Republic of Türkiye',
    legislature_speaker: 'Speaker of the Grand National Assembly',
    upper_house_leader: null,
    governing_party_ideology: 'Islamist-nationalist conservatism',
    ground_forces_branch: 'Turkish Land Forces',
    maritime_branch: 'Turkish Naval Forces',
    air_branch: 'Turkish Air Force',
    marine_branch: null,
    space_branch: 'Turkish Space Agency',
    paramilitary_branch: 'Gendarmerie General Command',
    coast_guard_branch: 'Coast Guard Command',
    cyber_branch: 'Presidency of Digital Transformation',
    intel_branch: 'National Intelligence Organisation',
    strategic_nuclear_branch: null,
    armed_forces_name: 'Turkish Armed Forces',
    military_chief_title: 'Chief of the Turkish General Staff',
    coalition_name: 'NATO eastern anchor',
    main_export: 'motor vehicles and machinery',
    main_import: 'machinery and gold',
    major_industry: 'automotive and textile manufacturing',
    city_name: 'Istanbul',
    state_name: 'Istanbul Province',
    locale_type: 'transcontinental megacity',
    locale_name: 'Istanbul',
    region_type: 'Anatolian crossroads',
    terrain: 'Anatolian plateau and Aegean coast',
    short_distance: '200 kilometres',
    medium_distance: '700 kilometres',
    long_distance: '1,800 kilometres',
    scenario_theme: 'strategic positioning',
    crisis_type: 'migration and refugee crisis',
    regional_bloc: 'NATO',
  },
  us: {
    head_of_state_title: 'President of the United States',
    legislature_speaker: 'Speaker of the House of Representatives',
    upper_house_leader: 'President pro tempore of the Senate',
    governing_party_ideology: 'right-wing nationalist populism',
    ground_forces_branch: 'US Army',
    maritime_branch: 'US Navy',
    air_branch: 'US Air Force',
    marine_branch: 'US Marine Corps',
    space_branch: 'US Space Force',
    paramilitary_branch: null,
    coast_guard_branch: 'US Coast Guard',
    cyber_branch: 'US Cyber Command',
    intel_branch: 'National Security Agency',
    strategic_nuclear_branch: 'US Strategic Command',
    armed_forces_name: 'US Armed Forces',
    military_chief_title: 'Chairman of the Joint Chiefs of Staff',
    coalition_name: 'NATO',
    main_export: 'technology and aerospace products',
    main_import: 'consumer electronics and vehicles',
    major_industry: 'technology and financial services',
    city_name: 'Chicago',
    state_name: 'Texas',
    locale_type: 'major metropolitan area',
    locale_name: 'Chicago',
    region_type: 'North American continent',
    terrain: 'diverse continental geography',
    short_distance: '500 kilometres',
    medium_distance: '2,000 kilometres',
    long_distance: '5,000 kilometres',
    scenario_theme: 'global leadership',
    crisis_type: 'domestic political crisis',
    regional_bloc: 'G7',
  },
  ua: {
    leader_title: 'President',
    head_of_state_title: 'President',
    country_adjective: 'Ukrainian',
    country_full_name: 'Ukraine',
    legislature: 'Verkhovna Rada',
    upper_house: null,
    lower_house: 'Verkhovna Rada',
    governing_party: 'Servant of the People',
    governing_party_short: 'Sluga Narodu',
    opposition_party: 'European Solidarity',
    central_bank: 'National Bank of Ukraine',
    currency: 'Ukrainian Hryvnia',
    currency_code: 'UAH',
    armed_forces_name: 'Armed Forces of Ukraine',
    ground_forces_branch: 'Ukrainian Ground Forces',
    maritime_branch: 'Ukrainian Naval Forces',
    air_branch: 'Ukrainian Air Force',
    special_forces: 'Special Operations Forces of Ukraine',
    paramilitary_branch: 'National Guard of Ukraine',
    intelligence_agency: 'Security Service of Ukraine',
    domestic_intelligence: 'Department of Counterintelligence',
    security_council: 'National Security and Defence Council',
    police_force: 'National Police of Ukraine',
    military_chief_title: 'Commander-in-Chief of the Armed Forces',
    press_role: 'Presidential Spokesperson',
    supreme_court: 'Supreme Court of Ukraine',
    attorney_general: 'Prosecutor General of Ukraine',
    audit_body: 'Accounting Chamber of Ukraine',
    major_industry: 'agriculture and defence manufacturing',
    economic_bloc: 'EU Candidate',
    primary_ally: 'United States',
    primary_adversary: 'Russia',
    border_rival_country: 'Russia',
    key_alliance: 'NATO Partnership',
  },
  za: {
    leader_title: 'President',
    head_of_state_title: 'President',
    country_adjective: 'South African',
    country_full_name: 'Republic of South Africa',
    legislature: 'Parliament',
    upper_house: 'National Council of Provinces',
    lower_house: 'National Assembly',
    governing_party: 'African National Congress',
    governing_party_short: 'ANC',
    opposition_party: 'Democratic Alliance',
    central_bank: 'South African Reserve Bank',
    currency: 'South African Rand',
    currency_code: 'ZAR',
    armed_forces_name: 'South African National Defence Force',
    ground_forces_branch: 'South African Army',
    maritime_branch: 'South African Navy',
    air_branch: 'South African Air Force',
    intelligence_agency: 'State Security Agency',
    domestic_intelligence: 'State Security Agency — Domestic Branch',
    security_council: 'National Security Council',
    police_force: 'South African Police Service',
    military_chief_title: 'Chief of the SANDF',
    press_role: 'Presidential Spokesperson',
    supreme_court: 'Constitutional Court of South Africa',
    attorney_general: 'National Director of Public Prosecutions',
    audit_body: 'Auditor-General of South Africa',
    major_industry: 'mining and minerals',
    economic_bloc: 'BRICS',
    primary_ally: 'China',
    primary_adversary: null,
    border_rival_country: null,
    key_alliance: 'African Union',
  },
  id: {
    leader_title: 'President',
    head_of_state_title: 'President',
    country_adjective: 'Indonesian',
    country_full_name: 'Republic of Indonesia',
    legislature: 'People\'s Consultative Assembly',
    upper_house: 'Regional Representative Council',
    lower_house: 'People\'s Representative Council',
    governing_party: 'Gerindra Party',
    governing_party_short: 'Gerindra',
    opposition_party: 'Indonesian Democratic Party of Struggle',
    central_bank: 'Bank Indonesia',
    currency: 'Indonesian Rupiah',
    currency_code: 'IDR',
    armed_forces_name: 'Tentara Nasional Indonesia',
    ground_forces_branch: 'TNI Angkatan Darat',
    maritime_branch: 'TNI Angkatan Laut',
    air_branch: 'TNI Angkatan Udara',
    special_forces: 'Korps Marinir',
    intelligence_agency: 'Badan Intelijen Negara',
    domestic_intelligence: 'Badan Intelijen dan Keamanan POLRI',
    security_council: 'Dewan Ketahanan Nasional',
    police_force: 'Kepolisian Negara Republik Indonesia',
    military_chief_title: 'Panglima TNI',
    press_role: 'Presidential Spokesperson',
    supreme_court: 'Mahkamah Agung',
    attorney_general: 'Jaksa Agung Republik Indonesia',
    audit_body: 'Badan Pemeriksa Keuangan',
    major_industry: 'palm oil and natural resources',
    economic_bloc: 'ASEAN',
    primary_ally: 'Australia',
    primary_adversary: null,
    border_rival_country: null,
    key_alliance: 'ASEAN',
  },
  sg: {
    leader_title: 'Prime Minister',
    head_of_state_title: 'President',
    country_adjective: 'Singaporean',
    country_full_name: 'Republic of Singapore',
    legislature: 'Parliament of Singapore',
    upper_house: null,
    lower_house: 'Parliament of Singapore',
    governing_party: "People's Action Party",
    governing_party_short: 'PAP',
    opposition_party: "Workers' Party",
    central_bank: 'Monetary Authority of Singapore',
    currency: 'Singapore Dollar',
    currency_code: 'SGD',
    armed_forces_name: 'Singapore Armed Forces',
    ground_forces_branch: 'Singapore Army',
    maritime_branch: 'Republic of Singapore Navy',
    air_branch: 'Republic of Singapore Air Force',
    intelligence_agency: 'Singapore Intelligence Service',
    domestic_intelligence: 'Internal Security Department',
    security_council: 'National Security Coordination Secretariat',
    police_force: 'Singapore Police Force',
    military_chief_title: 'Chief of Defence Force',
    press_role: 'Press Secretary to the Prime Minister',
    supreme_court: 'Supreme Court of Singapore',
    attorney_general: 'Attorney-General of Singapore',
    audit_body: 'Auditor-General\'s Office',
    major_industry: 'financial services and trade',
    economic_bloc: 'ASEAN',
    primary_ally: 'United States',
    primary_adversary: null,
    border_rival_country: null,
    key_alliance: 'ASEAN',
  },
  eg: {
    leader_title: 'President',
    head_of_state_title: 'President',
    country_adjective: 'Egyptian',
    country_full_name: 'Arab Republic of Egypt',
    legislature: 'Parliament',
    upper_house: 'Senate',
    lower_house: 'House of Representatives',
    governing_party: 'Nation Future Party',
    governing_party_short: 'Nation Future',
    opposition_party: 'Wafd Party',
    central_bank: 'Central Bank of Egypt',
    currency: 'Egyptian Pound',
    currency_code: 'EGP',
    armed_forces_name: 'Egyptian Armed Forces',
    ground_forces_branch: 'Egyptian Army',
    maritime_branch: 'Egyptian Navy',
    air_branch: 'Egyptian Air Force',
    paramilitary_branch: 'Egyptian Air Defense Command',
    intelligence_agency: 'General Intelligence Service',
    domestic_intelligence: 'National Security Sector',
    security_council: 'National Defence Council',
    police_force: 'Egyptian National Police',
    military_chief_title: 'Chief of Staff of the Armed Forces',
    press_role: 'Presidential Spokesperson',
    supreme_court: 'Supreme Constitutional Court',
    attorney_general: 'Attorney General of Egypt',
    audit_body: 'Central Auditing Organization',
    major_industry: 'tourism and Suez Canal revenues',
    economic_bloc: 'Arab League',
    primary_ally: 'Saudi Arabia',
    primary_adversary: 'Iran',
    border_rival_country: null,
    key_alliance: 'Arab League',
  },
};

// ── Main ───────────────────────────────────────────────────────────────────

async function main(): Promise<void> {
  initializeApp();
  const db = getFirestore();

  const snap = await db.collection('countries').get();
  console.log(`Found ${snap.size} countries. Mode: ${WRITE ? 'WRITE' : 'DRY RUN'}`);

  let updated = 0;
  let skipped = 0;
  const missing: string[] = [];

  for (const doc of snap.docs) {
    const id = doc.id;
    const newTokens = COUNTRY_DATA[id];

    if (!newTokens) {
      missing.push(id);
      continue;
    }

    const existing = (doc.data().tokens ?? {}) as Record<string, string | null>;
    const patch: Record<string, string | null> = {};

    for (const [key, value] of Object.entries(newTokens)) {
      if (!(key in existing) || existing[key] === undefined) {
        patch[key] = value;
      }
      // never overwrite an existing non-null value
    }

    if (Object.keys(patch).length === 0) {
      skipped++;
      continue;
    }

    if (WRITE) {
      await doc.ref.update({ tokens: { ...existing, ...patch } });
    } else {
      const addedKeys = Object.keys(patch).join(', ');
      console.log(`  ${id}: would add ${Object.keys(patch).length} tokens [${addedKeys}]`);
    }
    updated++;
  }

  console.log(`\nSummary: ${updated} countries to update, ${skipped} already complete`);
  if (missing.length > 0) {
    console.warn(`WARNING: no data defined for country IDs: ${missing.join(', ')}`);
  }
  if (!WRITE) {
    console.log('\nDry run complete. Pass --write to apply changes.');
  } else {
    console.log('Write complete.');
  }
}

if (require.main === module) {
  main().catch(console.error).finally(() => process.exit(0));
}
