import { initializeApp } from 'firebase-admin/app';
import { getFirestore, FieldValue } from 'firebase-admin/firestore';

import { deriveCountryAmountValues } from '../functions/src/lib/country-token-derivation';
import { COUNTRY_DATA } from './populate-country-tokens';

const WRITE = process.argv.includes('--write');

type CountrySeed = {
  name: string;
  region: string;
  facts: {
    schema_version: 2;
    baseline_id: string;
    demographics: {
      population_total: number;
      source_year: number;
    };
    economy: {
      gdp_nominal_usd: number;
      source_year: number;
      currency_name: string;
      currency_code: string;
      central_bank?: string;
      primary_export?: string;
      primary_import?: string;
      major_industry?: string;
    };
    institutions: {
      executive: {
        leader_title?: string;
        head_of_state_title?: string;
        vice_leader_title?: string;
      };
      legislature: {
        legislature?: string;
        lower_house?: string | null;
        upper_house?: string | null;
      };
      office_titles: {
        legislature_speaker?: string | null;
        upper_house_leader?: string | null;
      };
    };
    geography: {
      capital_city: string;
    };
  };
};

const COUNTRY_FACTS: Record<string, CountrySeed> = {
  ar: { name: 'Argentina', region: 'South America', facts: { schema_version: 2, baseline_id: 'ar', demographics: { population_total: 46_600_000, source_year: 2024 }, economy: { gdp_nominal_usd: 640_000_000_000, source_year: 2024, currency_name: 'Argentine peso', currency_code: 'ARS', central_bank: 'Central Bank of the Argentine Republic' }, institutions: { executive: { leader_title: 'President', head_of_state_title: 'President of the Argentine Nation', vice_leader_title: 'Vice President' }, legislature: { legislature: 'National Congress', lower_house: 'Chamber of Deputies', upper_house: 'Senate' }, office_titles: { legislature_speaker: COUNTRY_DATA.ar.legislature_speaker, upper_house_leader: COUNTRY_DATA.ar.upper_house_leader } }, geography: { capital_city: 'Buenos Aires' } } },
  au: { name: 'Australia', region: 'Oceania', facts: { schema_version: 2, baseline_id: 'au', demographics: { population_total: 26_900_000, source_year: 2024 }, economy: { gdp_nominal_usd: 1_720_000_000_000, source_year: 2024, currency_name: 'Australian dollar', currency_code: 'AUD', central_bank: 'Reserve Bank of Australia' }, institutions: { executive: { leader_title: 'Prime Minister', head_of_state_title: 'Governor-General of Australia', vice_leader_title: 'Deputy Prime Minister' }, legislature: { legislature: 'Parliament of Australia', lower_house: 'House of Representatives', upper_house: 'Senate' }, office_titles: { legislature_speaker: COUNTRY_DATA.au.legislature_speaker, upper_house_leader: COUNTRY_DATA.au.upper_house_leader } }, geography: { capital_city: 'Canberra' } } },
  bd: { name: 'Bangladesh', region: 'South Asia', facts: { schema_version: 2, baseline_id: 'bd', demographics: { population_total: 173_000_000, source_year: 2024 }, economy: { gdp_nominal_usd: 455_000_000_000, source_year: 2024, currency_name: 'Bangladeshi taka', currency_code: 'BDT', central_bank: 'Bangladesh Bank' }, institutions: { executive: { leader_title: 'Prime Minister', head_of_state_title: 'President of Bangladesh' }, legislature: { legislature: 'Jatiya Sangsad', lower_house: 'Jatiya Sangsad', upper_house: null }, office_titles: { legislature_speaker: COUNTRY_DATA.bd.legislature_speaker, upper_house_leader: COUNTRY_DATA.bd.upper_house_leader } }, geography: { capital_city: 'Dhaka' } } },
  br: { name: 'Brazil', region: 'South America', facts: { schema_version: 2, baseline_id: 'br', demographics: { population_total: 203_000_000, source_year: 2024 }, economy: { gdp_nominal_usd: 2_170_000_000_000, source_year: 2024, currency_name: 'Brazilian real', currency_code: 'BRL', central_bank: 'Central Bank of Brazil' }, institutions: { executive: { leader_title: 'President', head_of_state_title: 'President of the Federative Republic of Brazil', vice_leader_title: 'Vice President' }, legislature: { legislature: 'National Congress', lower_house: 'Chamber of Deputies', upper_house: 'Federal Senate' }, office_titles: { legislature_speaker: COUNTRY_DATA.br.legislature_speaker, upper_house_leader: COUNTRY_DATA.br.upper_house_leader } }, geography: { capital_city: 'Brasília' } } },
  ca: { name: 'Canada', region: 'North America', facts: { schema_version: 2, baseline_id: 'ca', demographics: { population_total: 41_000_000, source_year: 2024 }, economy: { gdp_nominal_usd: 2_240_000_000_000, source_year: 2024, currency_name: 'Canadian dollar', currency_code: 'CAD', central_bank: 'Bank of Canada' }, institutions: { executive: { leader_title: 'Prime Minister', head_of_state_title: 'Governor General of Canada', vice_leader_title: 'Deputy Prime Minister' }, legislature: { legislature: 'Parliament of Canada', lower_house: 'House of Commons', upper_house: 'Senate' }, office_titles: { legislature_speaker: COUNTRY_DATA.ca.legislature_speaker, upper_house_leader: COUNTRY_DATA.ca.upper_house_leader } }, geography: { capital_city: 'Ottawa' } } },
  ch: { name: 'Switzerland', region: 'Europe', facts: { schema_version: 2, baseline_id: 'ch', demographics: { population_total: 8_900_000, source_year: 2024 }, economy: { gdp_nominal_usd: 915_000_000_000, source_year: 2024, currency_name: 'Swiss franc', currency_code: 'CHF', central_bank: 'Swiss National Bank' }, institutions: { executive: { leader_title: 'President', head_of_state_title: 'President of the Swiss Confederation' }, legislature: { legislature: 'Federal Assembly', lower_house: 'National Council', upper_house: 'Council of States' }, office_titles: { legislature_speaker: COUNTRY_DATA.ch.legislature_speaker, upper_house_leader: COUNTRY_DATA.ch.upper_house_leader } }, geography: { capital_city: 'Bern' } } },
  cl: { name: 'Chile', region: 'South America', facts: { schema_version: 2, baseline_id: 'cl', demographics: { population_total: 19_700_000, source_year: 2024 }, economy: { gdp_nominal_usd: 335_000_000_000, source_year: 2024, currency_name: 'Chilean peso', currency_code: 'CLP', central_bank: 'Central Bank of Chile' }, institutions: { executive: { leader_title: 'President', head_of_state_title: 'President of the Republic of Chile' }, legislature: { legislature: 'National Congress', lower_house: 'Chamber of Deputies', upper_house: 'Senate' }, office_titles: { legislature_speaker: COUNTRY_DATA.cl.legislature_speaker, upper_house_leader: COUNTRY_DATA.cl.upper_house_leader } }, geography: { capital_city: 'Santiago' } } },
  cn: { name: 'China', region: 'East Asia', facts: { schema_version: 2, baseline_id: 'cn', demographics: { population_total: 1_409_000_000, source_year: 2024 }, economy: { gdp_nominal_usd: 18_600_000_000_000, source_year: 2024, currency_name: 'Renminbi', currency_code: 'CNY', central_bank: 'People\'s Bank of China' }, institutions: { executive: { leader_title: 'President', head_of_state_title: 'President of the People\'s Republic of China' }, legislature: { legislature: 'National People\'s Congress', lower_house: 'National People\'s Congress', upper_house: null }, office_titles: { legislature_speaker: COUNTRY_DATA.cn.legislature_speaker, upper_house_leader: COUNTRY_DATA.cn.upper_house_leader } }, geography: { capital_city: 'Beijing' } } },
  co: { name: 'Colombia', region: 'South America', facts: { schema_version: 2, baseline_id: 'co', demographics: { population_total: 52_000_000, source_year: 2024 }, economy: { gdp_nominal_usd: 386_000_000_000, source_year: 2024, currency_name: 'Colombian peso', currency_code: 'COP', central_bank: 'Bank of the Republic' }, institutions: { executive: { leader_title: 'President', head_of_state_title: 'President of the Republic of Colombia', vice_leader_title: 'Vice President' }, legislature: { legislature: 'Congress of Colombia', lower_house: 'House of Representatives', upper_house: 'Senate' }, office_titles: { legislature_speaker: COUNTRY_DATA.co.legislature_speaker, upper_house_leader: COUNTRY_DATA.co.upper_house_leader } }, geography: { capital_city: 'Bogotá' } } },
  cu: { name: 'Cuba', region: 'Caribbean', facts: { schema_version: 2, baseline_id: 'cu', demographics: { population_total: 11_100_000, source_year: 2024 }, economy: { gdp_nominal_usd: 110_000_000_000, source_year: 2024, currency_name: 'Cuban peso', currency_code: 'CUP', central_bank: 'Central Bank of Cuba' }, institutions: { executive: { leader_title: 'President', head_of_state_title: 'President of Cuba' }, legislature: { legislature: 'National Assembly of People\'s Power', lower_house: 'National Assembly of People\'s Power', upper_house: null }, office_titles: { legislature_speaker: COUNTRY_DATA.cu.legislature_speaker, upper_house_leader: COUNTRY_DATA.cu.upper_house_leader } }, geography: { capital_city: 'Havana' } } },
  de: { name: 'Germany', region: 'Europe', facts: { schema_version: 2, baseline_id: 'de', demographics: { population_total: 84_400_000, source_year: 2024 }, economy: { gdp_nominal_usd: 4_700_000_000_000, source_year: 2024, currency_name: 'Euro', currency_code: 'EUR', central_bank: 'Deutsche Bundesbank' }, institutions: { executive: { leader_title: 'Chancellor', head_of_state_title: 'Federal President of Germany', vice_leader_title: 'Vice Chancellor' }, legislature: { legislature: 'Federal Parliament', lower_house: 'Bundestag', upper_house: 'Bundesrat' }, office_titles: { legislature_speaker: COUNTRY_DATA.de.legislature_speaker, upper_house_leader: COUNTRY_DATA.de.upper_house_leader } }, geography: { capital_city: 'Berlin' } } },
  eg: { name: 'Egypt', region: 'Africa', facts: { schema_version: 2, baseline_id: 'eg', demographics: { population_total: 114_000_000, source_year: 2024 }, economy: { gdp_nominal_usd: 395_000_000_000, source_year: 2024, currency_name: 'Egyptian pound', currency_code: 'EGP', central_bank: 'Central Bank of Egypt' }, institutions: { executive: { leader_title: 'President', head_of_state_title: 'President of the Arab Republic of Egypt' }, legislature: { legislature: 'Parliament of Egypt', lower_house: 'House of Representatives', upper_house: 'Senate' }, office_titles: { legislature_speaker: COUNTRY_DATA.eg.legislature_speaker, upper_house_leader: COUNTRY_DATA.eg.upper_house_leader } }, geography: { capital_city: 'Cairo' } } },
  es: { name: 'Spain', region: 'Europe', facts: { schema_version: 2, baseline_id: 'es', demographics: { population_total: 48_600_000, source_year: 2024 }, economy: { gdp_nominal_usd: 1_620_000_000_000, source_year: 2024, currency_name: 'Euro', currency_code: 'EUR', central_bank: 'Bank of Spain' }, institutions: { executive: { leader_title: 'Prime Minister', head_of_state_title: 'King of Spain', vice_leader_title: 'Deputy Prime Minister' }, legislature: { legislature: 'Cortes Generales', lower_house: 'Congress of Deputies', upper_house: 'Senate' }, office_titles: { legislature_speaker: COUNTRY_DATA.es.legislature_speaker, upper_house_leader: COUNTRY_DATA.es.upper_house_leader } }, geography: { capital_city: 'Madrid' } } },
  fr: { name: 'France', region: 'Europe', facts: { schema_version: 2, baseline_id: 'fr', demographics: { population_total: 68_400_000, source_year: 2024 }, economy: { gdp_nominal_usd: 3_210_000_000_000, source_year: 2024, currency_name: 'Euro', currency_code: 'EUR', central_bank: 'Bank of France' }, institutions: { executive: { leader_title: 'President', head_of_state_title: 'President of the French Republic', vice_leader_title: 'Prime Minister' }, legislature: { legislature: 'French Parliament', lower_house: 'National Assembly', upper_house: 'Senate' }, office_titles: { legislature_speaker: COUNTRY_DATA.fr.legislature_speaker, upper_house_leader: COUNTRY_DATA.fr.upper_house_leader } }, geography: { capital_city: 'Paris' } } },
  gb: { name: 'United Kingdom', region: 'Europe', facts: { schema_version: 2, baseline_id: 'gb', demographics: { population_total: 69_500_000, source_year: 2024 }, economy: { gdp_nominal_usd: 3_580_000_000_000, source_year: 2024, currency_name: 'Pound sterling', currency_code: 'GBP', central_bank: 'Bank of England' }, institutions: { executive: { leader_title: 'Prime Minister', head_of_state_title: 'His Majesty the King', vice_leader_title: 'Deputy Prime Minister' }, legislature: { legislature: 'Parliament of the United Kingdom', lower_house: 'House of Commons', upper_house: 'House of Lords' }, office_titles: { legislature_speaker: COUNTRY_DATA.gb.legislature_speaker, upper_house_leader: COUNTRY_DATA.gb.upper_house_leader } }, geography: { capital_city: 'London' } } },
  gh: { name: 'Ghana', region: 'Africa', facts: { schema_version: 2, baseline_id: 'gh', demographics: { population_total: 34_700_000, source_year: 2024 }, economy: { gdp_nominal_usd: 77_000_000_000, source_year: 2024, currency_name: 'Ghanaian cedi', currency_code: 'GHS', central_bank: 'Bank of Ghana' }, institutions: { executive: { leader_title: 'President', head_of_state_title: 'President of the Republic of Ghana', vice_leader_title: 'Vice President' }, legislature: { legislature: 'Parliament of Ghana', lower_house: 'Parliament of Ghana', upper_house: null }, office_titles: { legislature_speaker: COUNTRY_DATA.gh.legislature_speaker, upper_house_leader: COUNTRY_DATA.gh.upper_house_leader } }, geography: { capital_city: 'Accra' } } },
  gr: { name: 'Greece', region: 'Europe', facts: { schema_version: 2, baseline_id: 'gr', demographics: { population_total: 10_300_000, source_year: 2024 }, economy: { gdp_nominal_usd: 250_000_000_000, source_year: 2024, currency_name: 'Euro', currency_code: 'EUR', central_bank: 'Bank of Greece' }, institutions: { executive: { leader_title: 'Prime Minister', head_of_state_title: 'President of the Hellenic Republic' }, legislature: { legislature: 'Hellenic Parliament', lower_house: 'Hellenic Parliament', upper_house: null }, office_titles: { legislature_speaker: COUNTRY_DATA.gr.legislature_speaker, upper_house_leader: COUNTRY_DATA.gr.upper_house_leader } }, geography: { capital_city: 'Athens' } } },
  hu: { name: 'Hungary', region: 'Europe', facts: { schema_version: 2, baseline_id: 'hu', demographics: { population_total: 9_600_000, source_year: 2024 }, economy: { gdp_nominal_usd: 220_000_000_000, source_year: 2024, currency_name: 'Hungarian forint', currency_code: 'HUF', central_bank: 'Hungarian National Bank' }, institutions: { executive: { leader_title: 'Prime Minister', head_of_state_title: 'President of Hungary' }, legislature: { legislature: 'National Assembly', lower_house: 'National Assembly', upper_house: null }, office_titles: { legislature_speaker: COUNTRY_DATA.hu.legislature_speaker, upper_house_leader: COUNTRY_DATA.hu.upper_house_leader } }, geography: { capital_city: 'Budapest' } } },
  id: { name: 'Indonesia', region: 'Southeast Asia', facts: { schema_version: 2, baseline_id: 'id', demographics: { population_total: 281_000_000, source_year: 2024 }, economy: { gdp_nominal_usd: 1_450_000_000_000, source_year: 2024, currency_name: 'Indonesian rupiah', currency_code: 'IDR', central_bank: 'Bank Indonesia' }, institutions: { executive: { leader_title: 'President', head_of_state_title: 'President of the Republic of Indonesia', vice_leader_title: 'Vice President' }, legislature: { legislature: 'People\'s Consultative Assembly', lower_house: 'People\'s Representative Council', upper_house: 'Regional Representatives Council' }, office_titles: { legislature_speaker: COUNTRY_DATA.id.legislature_speaker, upper_house_leader: COUNTRY_DATA.id.upper_house_leader } }, geography: { capital_city: 'Jakarta' } } },
  il: { name: 'Israel', region: 'Middle East', facts: { schema_version: 2, baseline_id: 'il', demographics: { population_total: 9_900_000, source_year: 2024 }, economy: { gdp_nominal_usd: 540_000_000_000, source_year: 2024, currency_name: 'Israeli new shekel', currency_code: 'ILS', central_bank: 'Bank of Israel' }, institutions: { executive: { leader_title: 'Prime Minister', head_of_state_title: 'President of the State of Israel', vice_leader_title: 'Deputy Prime Minister' }, legislature: { legislature: 'Knesset', lower_house: 'Knesset', upper_house: null }, office_titles: { legislature_speaker: COUNTRY_DATA.il.legislature_speaker, upper_house_leader: COUNTRY_DATA.il.upper_house_leader } }, geography: { capital_city: 'Jerusalem' } } },
  in: { name: 'India', region: 'South Asia', facts: { schema_version: 2, baseline_id: 'in', demographics: { population_total: 1_428_000_000, source_year: 2024 }, economy: { gdp_nominal_usd: 3_940_000_000_000, source_year: 2024, currency_name: 'Indian rupee', currency_code: 'INR', central_bank: 'Reserve Bank of India' }, institutions: { executive: { leader_title: 'Prime Minister', head_of_state_title: 'President of India', vice_leader_title: 'Deputy Prime Minister' }, legislature: { legislature: 'Parliament of India', lower_house: 'Lok Sabha', upper_house: 'Rajya Sabha' }, office_titles: { legislature_speaker: COUNTRY_DATA.in.legislature_speaker, upper_house_leader: COUNTRY_DATA.in.upper_house_leader } }, geography: { capital_city: 'New Delhi' } } },
  ir: { name: 'Iran', region: 'Middle East', facts: { schema_version: 2, baseline_id: 'ir', demographics: { population_total: 89_000_000, source_year: 2024 }, economy: { gdp_nominal_usd: 405_000_000_000, source_year: 2024, currency_name: 'Iranian rial', currency_code: 'IRR', central_bank: 'Central Bank of the Islamic Republic of Iran' }, institutions: { executive: { leader_title: 'President', head_of_state_title: 'Supreme Leader of Iran', vice_leader_title: 'First Vice President' }, legislature: { legislature: 'Islamic Consultative Assembly', lower_house: 'Islamic Consultative Assembly', upper_house: null }, office_titles: { legislature_speaker: COUNTRY_DATA.ir.legislature_speaker, upper_house_leader: COUNTRY_DATA.ir.upper_house_leader } }, geography: { capital_city: 'Tehran' } } },
  it: { name: 'Italy', region: 'Europe', facts: { schema_version: 2, baseline_id: 'it', demographics: { population_total: 58_900_000, source_year: 2024 }, economy: { gdp_nominal_usd: 2_420_000_000_000, source_year: 2024, currency_name: 'Euro', currency_code: 'EUR', central_bank: 'Bank of Italy' }, institutions: { executive: { leader_title: 'Prime Minister', head_of_state_title: 'President of the Italian Republic', vice_leader_title: 'Deputy Prime Minister' }, legislature: { legislature: 'Parliament of Italy', lower_house: 'Chamber of Deputies', upper_house: 'Senate of the Republic' }, office_titles: { legislature_speaker: COUNTRY_DATA.it.legislature_speaker, upper_house_leader: COUNTRY_DATA.it.upper_house_leader } }, geography: { capital_city: 'Rome' } } },
  jm: { name: 'Jamaica', region: 'Caribbean', facts: { schema_version: 2, baseline_id: 'jm', demographics: { population_total: 2_830_000, source_year: 2024 }, economy: { gdp_nominal_usd: 19_000_000_000, source_year: 2024, currency_name: 'Jamaican dollar', currency_code: 'JMD', central_bank: 'Bank of Jamaica' }, institutions: { executive: { leader_title: 'Prime Minister', head_of_state_title: 'Governor-General of Jamaica', vice_leader_title: 'Deputy Prime Minister' }, legislature: { legislature: 'Parliament of Jamaica', lower_house: 'House of Representatives', upper_house: 'Senate' }, office_titles: { legislature_speaker: COUNTRY_DATA.jm.legislature_speaker, upper_house_leader: COUNTRY_DATA.jm.upper_house_leader } }, geography: { capital_city: 'Kingston' } } },
  jp: { name: 'Japan', region: 'East Asia', facts: { schema_version: 2, baseline_id: 'jp', demographics: { population_total: 123_000_000, source_year: 2024 }, economy: { gdp_nominal_usd: 4_210_000_000_000, source_year: 2024, currency_name: 'Japanese yen', currency_code: 'JPY', central_bank: 'Bank of Japan' }, institutions: { executive: { leader_title: 'Prime Minister', head_of_state_title: 'Emperor of Japan', vice_leader_title: 'Chief Cabinet Secretary' }, legislature: { legislature: 'National Diet', lower_house: 'House of Representatives', upper_house: 'House of Councillors' }, office_titles: { legislature_speaker: COUNTRY_DATA.jp.legislature_speaker, upper_house_leader: COUNTRY_DATA.jp.upper_house_leader } }, geography: { capital_city: 'Tokyo' } } },
  ke: { name: 'Kenya', region: 'Africa', facts: { schema_version: 2, baseline_id: 'ke', demographics: { population_total: 55_300_000, source_year: 2024 }, economy: { gdp_nominal_usd: 122_000_000_000, source_year: 2024, currency_name: 'Kenyan shilling', currency_code: 'KES', central_bank: 'Central Bank of Kenya' }, institutions: { executive: { leader_title: 'President', head_of_state_title: 'President of the Republic of Kenya', vice_leader_title: 'Deputy President' }, legislature: { legislature: 'Parliament of Kenya', lower_house: 'National Assembly', upper_house: 'Senate' }, office_titles: { legislature_speaker: COUNTRY_DATA.ke.legislature_speaker, upper_house_leader: COUNTRY_DATA.ke.upper_house_leader } }, geography: { capital_city: 'Nairobi' } } },
  kp: { name: 'North Korea', region: 'East Asia', facts: { schema_version: 2, baseline_id: 'kp', demographics: { population_total: 26_000_000, source_year: 2024 }, economy: { gdp_nominal_usd: 32_000_000_000, source_year: 2024, currency_name: 'North Korean won', currency_code: 'KPW', central_bank: 'Central Bank of the Democratic People\'s Republic of Korea' }, institutions: { executive: { leader_title: 'Supreme Leader', head_of_state_title: 'Supreme Leader of the Democratic People\'s Republic of Korea' }, legislature: { legislature: 'Supreme People\'s Assembly', lower_house: 'Supreme People\'s Assembly', upper_house: null }, office_titles: { legislature_speaker: COUNTRY_DATA.kp.legislature_speaker, upper_house_leader: COUNTRY_DATA.kp.upper_house_leader } }, geography: { capital_city: 'Pyongyang' } } },
  kr: { name: 'South Korea', region: 'East Asia', facts: { schema_version: 2, baseline_id: 'kr', demographics: { population_total: 51_700_000, source_year: 2024 }, economy: { gdp_nominal_usd: 1_760_000_000_000, source_year: 2024, currency_name: 'South Korean won', currency_code: 'KRW', central_bank: 'Bank of Korea' }, institutions: { executive: { leader_title: 'President', head_of_state_title: 'President of the Republic of Korea', vice_leader_title: 'Prime Minister' }, legislature: { legislature: 'National Assembly', lower_house: 'National Assembly', upper_house: null }, office_titles: { legislature_speaker: COUNTRY_DATA.kr.legislature_speaker, upper_house_leader: COUNTRY_DATA.kr.upper_house_leader } }, geography: { capital_city: 'Seoul' } } },
  mx: { name: 'Mexico', region: 'North America', facts: { schema_version: 2, baseline_id: 'mx', demographics: { population_total: 129_000_000, source_year: 2024 }, economy: { gdp_nominal_usd: 1_850_000_000_000, source_year: 2024, currency_name: 'Mexican peso', currency_code: 'MXN', central_bank: 'Bank of Mexico' }, institutions: { executive: { leader_title: 'President', head_of_state_title: 'President of the United Mexican States' }, legislature: { legislature: 'Congress of the Union', lower_house: 'Chamber of Deputies', upper_house: 'Senate' }, office_titles: { legislature_speaker: COUNTRY_DATA.mx.legislature_speaker, upper_house_leader: COUNTRY_DATA.mx.upper_house_leader } }, geography: { capital_city: 'Mexico City' } } },
  my: { name: 'Malaysia', region: 'Southeast Asia', facts: { schema_version: 2, baseline_id: 'my', demographics: { population_total: 34_500_000, source_year: 2024 }, economy: { gdp_nominal_usd: 445_000_000_000, source_year: 2024, currency_name: 'Malaysian ringgit', currency_code: 'MYR', central_bank: 'Bank Negara Malaysia' }, institutions: { executive: { leader_title: 'Prime Minister', head_of_state_title: 'Yang di-Pertuan Agong of Malaysia', vice_leader_title: 'Deputy Prime Minister' }, legislature: { legislature: 'Parliament of Malaysia', lower_house: 'Dewan Rakyat', upper_house: 'Dewan Negara' }, office_titles: { legislature_speaker: COUNTRY_DATA.my.legislature_speaker, upper_house_leader: COUNTRY_DATA.my.upper_house_leader } }, geography: { capital_city: 'Kuala Lumpur' } } },
  ng: { name: 'Nigeria', region: 'Africa', facts: { schema_version: 2, baseline_id: 'ng', demographics: { population_total: 229_000_000, source_year: 2024 }, economy: { gdp_nominal_usd: 390_000_000_000, source_year: 2024, currency_name: 'Nigerian naira', currency_code: 'NGN', central_bank: 'Central Bank of Nigeria' }, institutions: { executive: { leader_title: 'President', head_of_state_title: 'President of the Federal Republic of Nigeria', vice_leader_title: 'Vice President' }, legislature: { legislature: 'National Assembly', lower_house: 'House of Representatives', upper_house: 'Senate' }, office_titles: { legislature_speaker: COUNTRY_DATA.ng.legislature_speaker, upper_house_leader: COUNTRY_DATA.ng.upper_house_leader } }, geography: { capital_city: 'Abuja' } } },
  nl: { name: 'Netherlands', region: 'Europe', facts: { schema_version: 2, baseline_id: 'nl', demographics: { population_total: 17_900_000, source_year: 2024 }, economy: { gdp_nominal_usd: 1_150_000_000_000, source_year: 2024, currency_name: 'Euro', currency_code: 'EUR', central_bank: 'De Nederlandsche Bank' }, institutions: { executive: { leader_title: 'Prime Minister', head_of_state_title: 'King of the Netherlands', vice_leader_title: 'Deputy Prime Minister' }, legislature: { legislature: 'States General', lower_house: 'House of Representatives', upper_house: 'Senate' }, office_titles: { legislature_speaker: COUNTRY_DATA.nl.legislature_speaker, upper_house_leader: COUNTRY_DATA.nl.upper_house_leader } }, geography: { capital_city: 'Amsterdam' } } },
  no: { name: 'Norway', region: 'Europe', facts: { schema_version: 2, baseline_id: 'no', demographics: { population_total: 5_600_000, source_year: 2024 }, economy: { gdp_nominal_usd: 505_000_000_000, source_year: 2024, currency_name: 'Norwegian krone', currency_code: 'NOK', central_bank: 'Norges Bank' }, institutions: { executive: { leader_title: 'Prime Minister', head_of_state_title: 'King of Norway', vice_leader_title: 'Deputy Prime Minister' }, legislature: { legislature: 'Storting', lower_house: 'Storting', upper_house: null }, office_titles: { legislature_speaker: COUNTRY_DATA.no.legislature_speaker, upper_house_leader: COUNTRY_DATA.no.upper_house_leader } }, geography: { capital_city: 'Oslo' } } },
  nz: { name: 'New Zealand', region: 'Oceania', facts: { schema_version: 2, baseline_id: 'nz', demographics: { population_total: 5_300_000, source_year: 2024 }, economy: { gdp_nominal_usd: 255_000_000_000, source_year: 2024, currency_name: 'New Zealand dollar', currency_code: 'NZD', central_bank: 'Reserve Bank of New Zealand' }, institutions: { executive: { leader_title: 'Prime Minister', head_of_state_title: 'Governor-General of New Zealand', vice_leader_title: 'Deputy Prime Minister' }, legislature: { legislature: 'New Zealand Parliament', lower_house: 'House of Representatives', upper_house: null }, office_titles: { legislature_speaker: COUNTRY_DATA.nz.legislature_speaker, upper_house_leader: COUNTRY_DATA.nz.upper_house_leader } }, geography: { capital_city: 'Wellington' } } },
  ph: { name: 'Philippines', region: 'Southeast Asia', facts: { schema_version: 2, baseline_id: 'ph', demographics: { population_total: 117_000_000, source_year: 2024 }, economy: { gdp_nominal_usd: 470_000_000_000, source_year: 2024, currency_name: 'Philippine peso', currency_code: 'PHP', central_bank: 'Bangko Sentral ng Pilipinas' }, institutions: { executive: { leader_title: 'President', head_of_state_title: 'President of the Philippines', vice_leader_title: 'Vice President' }, legislature: { legislature: 'Congress of the Philippines', lower_house: 'House of Representatives', upper_house: 'Senate' }, office_titles: { legislature_speaker: COUNTRY_DATA.ph.legislature_speaker, upper_house_leader: COUNTRY_DATA.ph.upper_house_leader } }, geography: { capital_city: 'Manila' } } },
  pk: { name: 'Pakistan', region: 'South Asia', facts: { schema_version: 2, baseline_id: 'pk', demographics: { population_total: 241_000_000, source_year: 2024 }, economy: { gdp_nominal_usd: 375_000_000_000, source_year: 2024, currency_name: 'Pakistani rupee', currency_code: 'PKR', central_bank: 'State Bank of Pakistan' }, institutions: { executive: { leader_title: 'Prime Minister', head_of_state_title: 'President of Pakistan', vice_leader_title: 'Deputy Prime Minister' }, legislature: { legislature: 'Parliament of Pakistan', lower_house: 'National Assembly', upper_house: 'Senate' }, office_titles: { legislature_speaker: COUNTRY_DATA.pk.legislature_speaker, upper_house_leader: COUNTRY_DATA.pk.upper_house_leader } }, geography: { capital_city: 'Islamabad' } } },
  pl: { name: 'Poland', region: 'Europe', facts: { schema_version: 2, baseline_id: 'pl', demographics: { population_total: 37_500_000, source_year: 2024 }, economy: { gdp_nominal_usd: 845_000_000_000, source_year: 2024, currency_name: 'Polish złoty', currency_code: 'PLN', central_bank: 'National Bank of Poland' }, institutions: { executive: { leader_title: 'Prime Minister', head_of_state_title: 'President of the Republic of Poland', vice_leader_title: 'Deputy Prime Minister' }, legislature: { legislature: 'National Assembly', lower_house: 'Sejm', upper_house: 'Senate' }, office_titles: { legislature_speaker: COUNTRY_DATA.pl.legislature_speaker, upper_house_leader: COUNTRY_DATA.pl.upper_house_leader } }, geography: { capital_city: 'Warsaw' } } },
  pt: { name: 'Portugal', region: 'Europe', facts: { schema_version: 2, baseline_id: 'pt', demographics: { population_total: 10_400_000, source_year: 2024 }, economy: { gdp_nominal_usd: 305_000_000_000, source_year: 2024, currency_name: 'Euro', currency_code: 'EUR', central_bank: 'Bank of Portugal' }, institutions: { executive: { leader_title: 'Prime Minister', head_of_state_title: 'President of the Portuguese Republic' }, legislature: { legislature: 'Assembly of the Republic', lower_house: 'Assembly of the Republic', upper_house: null }, office_titles: { legislature_speaker: COUNTRY_DATA.pt.legislature_speaker, upper_house_leader: COUNTRY_DATA.pt.upper_house_leader } }, geography: { capital_city: 'Lisbon' } } },
  qa: { name: 'Qatar', region: 'Middle East', facts: { schema_version: 2, baseline_id: 'qa', demographics: { population_total: 3_000_000, source_year: 2024 }, economy: { gdp_nominal_usd: 235_000_000_000, source_year: 2024, currency_name: 'Qatari riyal', currency_code: 'QAR', central_bank: 'Qatar Central Bank' }, institutions: { executive: { leader_title: 'Emir', head_of_state_title: 'Emir of the State of Qatar' }, legislature: { legislature: 'Consultative Assembly', lower_house: 'Consultative Assembly', upper_house: null }, office_titles: { legislature_speaker: COUNTRY_DATA.qa.legislature_speaker, upper_house_leader: COUNTRY_DATA.qa.upper_house_leader } }, geography: { capital_city: 'Doha' } } },
  ru: { name: 'Russia', region: 'Eurasia', facts: { schema_version: 2, baseline_id: 'ru', demographics: { population_total: 144_000_000, source_year: 2024 }, economy: { gdp_nominal_usd: 2_020_000_000_000, source_year: 2024, currency_name: 'Russian ruble', currency_code: 'RUB', central_bank: 'Bank of Russia' }, institutions: { executive: { leader_title: 'President', head_of_state_title: 'President of the Russian Federation', vice_leader_title: 'Prime Minister' }, legislature: { legislature: 'Federal Assembly', lower_house: 'State Duma', upper_house: 'Federation Council' }, office_titles: { legislature_speaker: COUNTRY_DATA.ru.legislature_speaker, upper_house_leader: COUNTRY_DATA.ru.upper_house_leader } }, geography: { capital_city: 'Moscow' } } },
  sa: { name: 'Saudi Arabia', region: 'Middle East', facts: { schema_version: 2, baseline_id: 'sa', demographics: { population_total: 37_000_000, source_year: 2024 }, economy: { gdp_nominal_usd: 1_100_000_000_000, source_year: 2024, currency_name: 'Saudi riyal', currency_code: 'SAR', central_bank: 'Saudi Central Bank' }, institutions: { executive: { leader_title: 'King', head_of_state_title: 'King of Saudi Arabia', vice_leader_title: 'Crown Prince' }, legislature: { legislature: 'Consultative Assembly', lower_house: 'Consultative Assembly', upper_house: null }, office_titles: { legislature_speaker: COUNTRY_DATA.sa.legislature_speaker, upper_house_leader: COUNTRY_DATA.sa.upper_house_leader } }, geography: { capital_city: 'Riyadh' } } },
  se: { name: 'Sweden', region: 'Europe', facts: { schema_version: 2, baseline_id: 'se', demographics: { population_total: 10_600_000, source_year: 2024 }, economy: { gdp_nominal_usd: 610_000_000_000, source_year: 2024, currency_name: 'Swedish krona', currency_code: 'SEK', central_bank: 'Sveriges Riksbank' }, institutions: { executive: { leader_title: 'Prime Minister', head_of_state_title: 'King of Sweden', vice_leader_title: 'Deputy Prime Minister' }, legislature: { legislature: 'Riksdag', lower_house: 'Riksdag', upper_house: null }, office_titles: { legislature_speaker: COUNTRY_DATA.se.legislature_speaker, upper_house_leader: COUNTRY_DATA.se.upper_house_leader } }, geography: { capital_city: 'Stockholm' } } },
  sg: { name: 'Singapore', region: 'Southeast Asia', facts: { schema_version: 2, baseline_id: 'sg', demographics: { population_total: 6_000_000, source_year: 2024 }, economy: { gdp_nominal_usd: 545_000_000_000, source_year: 2024, currency_name: 'Singapore dollar', currency_code: 'SGD', central_bank: 'Monetary Authority of Singapore' }, institutions: { executive: { leader_title: 'Prime Minister', head_of_state_title: 'President of the Republic of Singapore', vice_leader_title: 'Deputy Prime Minister' }, legislature: { legislature: 'Parliament of Singapore', lower_house: 'Parliament of Singapore', upper_house: null }, office_titles: { legislature_speaker: COUNTRY_DATA.sg.legislature_speaker, upper_house_leader: COUNTRY_DATA.sg.upper_house_leader } }, geography: { capital_city: 'Singapore' } } },
  th: { name: 'Thailand', region: 'Southeast Asia', facts: { schema_version: 2, baseline_id: 'th', demographics: { population_total: 71_700_000, source_year: 2024 }, economy: { gdp_nominal_usd: 515_000_000_000, source_year: 2024, currency_name: 'Thai baht', currency_code: 'THB', central_bank: 'Bank of Thailand' }, institutions: { executive: { leader_title: 'Prime Minister', head_of_state_title: 'King of Thailand', vice_leader_title: 'Deputy Prime Minister' }, legislature: { legislature: 'National Assembly', lower_house: 'House of Representatives', upper_house: 'Senate' }, office_titles: { legislature_speaker: COUNTRY_DATA.th.legislature_speaker, upper_house_leader: COUNTRY_DATA.th.upper_house_leader } }, geography: { capital_city: 'Bangkok' } } },
  tr: { name: 'Türkiye', region: 'Eurasia', facts: { schema_version: 2, baseline_id: 'tr', demographics: { population_total: 85_700_000, source_year: 2024 }, economy: { gdp_nominal_usd: 1_110_000_000_000, source_year: 2024, currency_name: 'Turkish lira', currency_code: 'TRY', central_bank: 'Central Bank of the Republic of Türkiye' }, institutions: { executive: { leader_title: 'President', head_of_state_title: 'President of the Republic of Türkiye', vice_leader_title: 'Vice President' }, legislature: { legislature: 'Grand National Assembly of Türkiye', lower_house: 'Grand National Assembly of Türkiye', upper_house: null }, office_titles: { legislature_speaker: COUNTRY_DATA.tr.legislature_speaker, upper_house_leader: COUNTRY_DATA.tr.upper_house_leader } }, geography: { capital_city: 'Ankara' } } },
  ua: { name: 'Ukraine', region: 'Europe', facts: { schema_version: 2, baseline_id: 'ua', demographics: { population_total: 37_000_000, source_year: 2024 }, economy: { gdp_nominal_usd: 190_000_000_000, source_year: 2024, currency_name: 'Ukrainian hryvnia', currency_code: 'UAH', central_bank: 'National Bank of Ukraine' }, institutions: { executive: { leader_title: 'President', head_of_state_title: 'President of Ukraine' }, legislature: { legislature: 'Verkhovna Rada', lower_house: 'Verkhovna Rada', upper_house: null }, office_titles: { legislature_speaker: COUNTRY_DATA.ua.legislature_speaker, upper_house_leader: COUNTRY_DATA.ua.upper_house_leader } }, geography: { capital_city: 'Kyiv' } } },
  us: { name: 'United States', region: 'North America', facts: { schema_version: 2, baseline_id: 'us', demographics: { population_total: 340_000_000, source_year: 2024 }, economy: { gdp_nominal_usd: 29_000_000_000_000, source_year: 2024, currency_name: 'US dollar', currency_code: 'USD', central_bank: 'Federal Reserve' }, institutions: { executive: { leader_title: 'President', head_of_state_title: 'President of the United States', vice_leader_title: 'Vice President' }, legislature: { legislature: 'Congress', lower_house: 'House of Representatives', upper_house: 'Senate' }, office_titles: { legislature_speaker: COUNTRY_DATA.us.legislature_speaker, upper_house_leader: COUNTRY_DATA.us.upper_house_leader } }, geography: { capital_city: 'Washington, D.C.' } } },
  ve: { name: 'Venezuela', region: 'South America', facts: { schema_version: 2, baseline_id: 've', demographics: { population_total: 28_500_000, source_year: 2024 }, economy: { gdp_nominal_usd: 110_000_000_000, source_year: 2024, currency_name: 'Venezuelan bolívar', currency_code: 'VES', central_bank: 'Central Bank of Venezuela' }, institutions: { executive: { leader_title: 'President', head_of_state_title: 'President of the Bolivarian Republic of Venezuela' }, legislature: { legislature: 'National Assembly', lower_house: 'National Assembly', upper_house: null }, office_titles: { legislature_speaker: COUNTRY_DATA.ve.legislature_speaker, upper_house_leader: COUNTRY_DATA.ve.upper_house_leader } }, geography: { capital_city: 'Caracas' } } },
  vn: { name: 'Vietnam', region: 'Southeast Asia', facts: { schema_version: 2, baseline_id: 'vn', demographics: { population_total: 101_000_000, source_year: 2024 }, economy: { gdp_nominal_usd: 470_000_000_000, source_year: 2024, currency_name: 'Vietnamese đồng', currency_code: 'VND', central_bank: 'State Bank of Vietnam' }, institutions: { executive: { leader_title: 'Prime Minister', head_of_state_title: 'President of the Socialist Republic of Vietnam', vice_leader_title: 'Deputy Prime Minister' }, legislature: { legislature: 'National Assembly', lower_house: 'National Assembly', upper_house: null }, office_titles: { legislature_speaker: COUNTRY_DATA.vn.legislature_speaker, upper_house_leader: COUNTRY_DATA.vn.upper_house_leader } }, geography: { capital_city: 'Hanoi' } } },
  za: { name: 'South Africa', region: 'Africa', facts: { schema_version: 2, baseline_id: 'za', demographics: { population_total: 63_000_000, source_year: 2024 }, economy: { gdp_nominal_usd: 405_000_000_000, source_year: 2024, currency_name: 'South African rand', currency_code: 'ZAR', central_bank: 'South African Reserve Bank' }, institutions: { executive: { leader_title: 'President', head_of_state_title: 'President of the Republic of South Africa', vice_leader_title: 'Deputy President' }, legislature: { legislature: 'Parliament of South Africa', lower_house: 'National Assembly', upper_house: 'National Council of Provinces' }, office_titles: { legislature_speaker: COUNTRY_DATA.za.legislature_speaker, upper_house_leader: COUNTRY_DATA.za.upper_house_leader } }, geography: { capital_city: 'Pretoria' } } },
};

function buildFacts(countryId: string, seed: CountrySeed) {
  const tokenSeed = COUNTRY_DATA[countryId] ?? {};
  return {
    ...seed.facts,
    economy: {
      ...seed.facts.economy,
      primary_export: tokenSeed.main_export ?? seed.facts.economy.primary_export,
      primary_import: tokenSeed.main_import ?? seed.facts.economy.primary_import,
      major_industry: tokenSeed.major_industry ?? seed.facts.economy.major_industry,
    },
  };
}

async function main() {
  initializeApp();
  const db = getFirestore();
  const ids = Object.keys(COUNTRY_FACTS).sort();
  console.log(`Seeding ${ids.length} canonical country facts. Mode: ${WRITE ? 'WRITE' : 'DRY RUN'}`);

  for (const id of ids) {
    const seed = COUNTRY_FACTS[id];
    const facts = buildFacts(id, seed);
    const amounts = deriveCountryAmountValues({ id, facts });
    const payload = {
      name: seed.name,
      code: id.toUpperCase(),
      region: seed.region,
      facts,
      amounts,
      leaderTitle: FieldValue.delete(),
      leader: FieldValue.delete(),
      capital: FieldValue.delete(),
      attributes: FieldValue.delete(),
      population: FieldValue.delete(),
      economy: FieldValue.delete(),
      currentPopulation: FieldValue.delete(),
      gdp: FieldValue.delete(),
      populationMillions: FieldValue.delete(),
      gdpBillions: FieldValue.delete(),
    };

    if (!WRITE) {
      console.log(`${id}: ${seed.name} → ${facts.geography.capital_city}, pop=${facts.demographics.population_total}, gdp=${facts.economy.gdp_nominal_usd}, trade=${amounts.trade_value}`);
      continue;
    }

    await db.collection('countries').doc(id).set(payload, { merge: true });
    console.log(`Updated countries/${id}`);
  }

  console.log(WRITE ? 'Canonical country facts seeded.' : 'Dry run complete. Pass --write to apply changes.');
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
